coffeedapp2/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin


urlpatterns = patterns('',
    url(r'', include('core.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
import core.views as coreviews

urlpatterns = patterns('',
  url(r'^$', coreviews.LandingView.as_view()),
  url(r'locations/$', coreviews.LocationListView.as_view()),
  url(r'locations/(?P<pk>\d+)/detail/$', coreviews.LocationDetailView.as_view(), name='location_list'),
  url(r'locations/create/$', login_required(coreviews.LocationCreateView.as_view())),
  url(r'search/$', coreviews.SearchListView.as_view()),
  url(r'locations/(?P<pk>\d+)/update/$', login_required(coreviews.LocationUpdateView.as_view()), name='location_update'),
  url(r'locations/(?P<pk>\d+)/review/create/$', login_required(coreviews.ReviewCreateView.as_view()), name='review_create'),
  url(r'locations/(?P<pk>\d+)/review/update/$', login_required(coreviews.ReviewUpdateView.as_view()), name='review_update'),
  url(r'entrance/$', coreviews.entrance),
)

core/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models import Avg
from geoposition.fields import GeopositionField
import datetime 

import os
import uuid

RATING_CHOICES = (
	(0, 'None'),
	(1, '*'),
	(2, '**'),
	(3, '***'),
	(4, '****'),
	(5, '*****'),
)

YESNO_CHOICES = (
	(0, 'no'),
	(1, 'yes'),
)

def upload_to_location(instance, filename):
    blocks = filename.split('.')
    ext = blocks[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    instance.title = blocks[0]
    return os.path.join('uploads/', filename)

class Locations(models.Model):
    title = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    hours = models.TextField(null=True, blank=True)
    image_file = models.ImageField(upload_to=upload_to_location, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    alcohol = models.IntegerField(choices=YESNO_CHOICES, null=True, blank=True)
    position = GeopositionField(null=True, blank=True)

    def __unicode__(self):
        return self.title     

    def get_absolute_url(self):
    	return reverse(viewname="location_list", args=[self.id])

    def get_average_rating(self):
    	average = self.review_set.all().aggregate(Avg('rating'))['rating__avg']
    	if average == None:
    		return average
    	else:
    		return int(average)

    def get_reviews(self):
    	return self.review_set.all()

class Review(models.Model):
	location = models.ForeignKey(Locations)
	user = models.ForeignKey(User)
	description = models.TextField(null=True, blank=True)
	rating = models.IntegerField(choices=RATING_CHOICES, null=True, blank=True)
	# created_at originally = models.DateTimeField(auto_add_now = True)
	created_at = models.DateTimeField(default=datetime.datetime.now)

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from sitegate.decorators import redirect_signedin, sitegate_view
import core.models as coremodels


class LandingView(TemplateView):
	template_name = "base/index.html"


class LocationListView(ListView):
    model = coremodels.Locations
    template_name = "locations/list.html"


class SearchListView(LocationListView):
	def get_queryset(self):
		incoming_query_string = self.request.GET.get('query', '')
		return coremodels.Locations.objects.filter(title__icontains=incoming_query_string)


class LocationDetailView(DetailView):
    model = coremodels.Locations
    template_name = "locations/detail.html"
    context_object_name = 'location'

    def get_context_data(self, **kwargs):
    	context = super(LocationDetailView, self).get_context_data(**kwargs)
    	location = coremodels.Locations.objects.get(id=self.kwargs['pk'])
    	if self.request.user.is_authenticated():
    		user_reviews = coremodels.Review.objects.filter(location=location, user=self.request.user)
    		if user_reviews.count() > 0:
    			context['user_review'] = user_reviews[0]
    		else:
    			context['user_review'] = None
    	return context


class LocationCreateView(CreateView):
	model = coremodels.Locations
	template_name = "base/form.html"
	fields = "__all__"


class LocationUpdateView(UpdateView):
	model = coremodels.Locations
	template_name = "base/form.html"
	fields = "__all__"


class ReviewCreateView(CreateView):
	model = coremodels.Review
	template_name = "base/form.html"
	fields = ['description', 'rating']

	def form_valid(self, form):
		form.instance.user = self.request.user
		form.instance.location = coremodels.Locations.objects.get(id=self.kwargs['pk'])
		return super(ReviewCreateView, self).form_valid(form)

	def get_success_url(self):
		return self.object.location.get_absolute_url()


class ReviewUpdateView(UpdateView): 
	model = coremodels.Review
	template_name = "base/form.html"
	fields = ['description', 'rating']

	def get_object(self):
		return coremodels.Review.objects.get(location__id=self.kwargs['pk'], user=self.request.user)

	def get_success_url(self):
		return self.object.location.get_absolute_url()


@sitegate_view(widget_attrs={'class': 'form-control', 'placeholder': lambda f: f.label}, template='form_bootstrap3')
def entrance(request):
	return render(request, 'base/entrance.html', {'title': 'Sign In & Sign Up'})
	

templates/base/entrance.html
{% extends 'base/theme.html' %}
{% load sitegate %}
{% block main_content %}

<section id="services">
  <div class="container">
	<div class="row">
	  <div class="col-lg-6 text-center">
		<div class="my_signin_block">
		  <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Sign In</a></h2>
		  <h3 class="section-subheading text-muted">Welcome back!</h3>
		  {% sitegate_signin_form %}
		</div>
      </div>
      <br>
      <div class="col-lg-6 text-center">
 	    <div class="my_signup_block">
 	      <h2 class="section-heading"><a href="{{ location.get_absolute_url }}">Sign Up</a></h2>
		  <h3 class="section-subheading text-muted">Visit exotic places, and talk smack about them!</h3>
		  {% sitegate_signup_form %}
		</div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/base/form.html
{% extends "base/theme.html" %}
{% load widget_tweaks %}
{% block main_content %}
<div class="header-buffer"></div>
<section id="services">
	<div class="container">
		<div class="row">
			{% if form %}
			<div class="col-md-12">
				<form action='' method="post" enctype="multipart/form-data">{% csrf_token %}{{ form.media }}
				{% for field in form %}
					<div class="form-group warning">
						<label for="exampleInputFile">{{ field.label }}</label>
						{{ field|add_class:"form-control"}}
 						{% if field.help_text %}
 							<p class="help-block">{{ field.help_text }}</p>
 						{% endif %}
 					</div>
 					{% if field.errors %}
 						{% for error in field.errors %}
 							<div class="alert alert-danger" id="error_{{ field.name }}">{{ error|escape }}</div>
 						{% endfor %}
 					{% endif %}
 				{% endfor %}
 				<input type="submit" class="btn btn-success" role="button" value="{{ verb|default:"Submit" }}" />
 				</form>
			</div>
			{% endif %}
		</div>
	</div>
</section>
{% endblock %}

templates/base/rating.html
<div class="coffeed-rating">
{% if rating == 1 %}
<i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 2 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 3 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% elif rating == 4 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart-o"></i>
{% elif rating == 5 %}
<i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i><i class="fa fa-heart"></i>
{% else %}
<i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i><i class="fa fa-heart-o"></i>
{% endif %}
</div>

templates/base/review.html
<div class="row">
	<div class="col-md-8">
		<h2>{{ review.user.get_full_name }} <a class="subheading"> | {{ review.created_at | date }}</a></h2>
	</div>
	<div class="col-md-4 text-right">
		<h2>{% include "base/rating.html" with rating=review.rating %}</h2>
	</div>
</div>
<p>{{ review.description }}</p>

templates/base/theme.html
{% extends "base/index.html" %}

{% block navigation %}
	<li>
		<a class="page-scroll" href="/locations">Find a Coffee Shop</a>
	</li>
	{% if user.is_authenticated %}
	<li>
		<a class="page-scroll" href="/locations/create">Add a Location</a>
	</li>
	{% else %}
	<li>
		<a class="page-scroll" href="/entrance/">Log In</a>
	</li>
	{% endif %}

{% endblock %}

{% block main_content %}

{% endblock %}

templates/locations/detail.html
d{% extends "base/theme.html" %}
{% block main_content %}
<div class="row main-content">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="row">
      <div class="col-md-8">
        <h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
      </div>
      <div class="col-md-4 text-right">
        <h3>{% include "base/rating.html" with rating=location.get_average_rating %}</h3>
        <a type="button" href="{% url 'location_update' pk=location.id %}" class="btn btn-default pull-right">Edit</a>
        {% if user_review %}
        <a type="button" href="{% url 'review_update' pk=location.id %}" class="btn btn-default pull-right">Update Review</a>
        {% else %}
        <a type="button" href="{% url 'review_create' pk=location.id %}" class="btn btn-default pull-right">Create Review</a>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        {% if location.address %}
          <p><b>Location: </b>{{ location.address }}</p>
        {% endif %}
        {% if location.hours %}
          <p>{{ location.hours }}</p> 
        {% endif %}
        {% include "locations/specifics.html" with location=location %}
        {% if location.image_file %}
          <img class="img-responsive center-block" style="max-height: 400px;" src="{{ location.image_file.url }}"></img>
        {% endif %}
      </div>
    </div>
    <hr>
    <p>{{ location.description }}</p>
    <hr>
    <div class="row">
      <div class="col-md-12">
        {% for review in location.get_reviews %}
          {% include "base/review.html" with location=location %}
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
{% endblock %}

templates/locations/list.html
{% extends "base/theme.html" %}
{% block main_content %}
<div class="data-layer">
 <ul>
 {% for location in object_list %}
 <li class="location-data" data-latitude="{{ location.position.latitude }}" data-longitude="{{ location.position.longitude }}" data-id="{{ location.id }}">{{ location.title }}</li>
 {% endfor %}
 </ul>
</div>
<div id="map" class="wide-map">
</div>
<div class="row main-content">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    {% for location in object_list %}
    <div class="row">
        <div class="col-md-8">
          <h3><a href="{{ location.get_absolute_url }}">{{ location.title }}</a></h3>
        </div>
        <div class="col-md-4 text-right">
          <h3>{% include "base/rating.html" with rating=location.get_average_rating %}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        {% if location.address %}<p><b>Location: </b>{{ location.address }}</p>{% endif %}
        {% if location.hours %}<p>{{ location.hours }}</p> {% endif %}
        {% include "locations/specifics.html" with location=location %}
        {% if location.image_file %}
          <a href="{{ location.get_absolute_url }}"><img class="img-responsive center-block" style="max-height: 400px;" src="{{ location.image_file.url }}"></img></a>
        {% endif %}
        </div>
    </div>
    {% endfor %}
  </div>
  <div class="col-md-2"></div>
</div>
{% endblock %}

templates/locations/specifics.html
<div class="row">
	<div class="col-md-4">
		<p><b>Alcohol: </b>{% if location.alcohol %}{{ location.get_alcohol_display }}{% else %}----{% endif %}</p>
	</div>
</div>